### ISSUE TITLE
Create generic React Components.

### ISSUE THREAD

**Issue by nimish-gupta** [pesto-students/batch-12-WeConnect#5]

**Comment by nitishmittal1990** [comment]
- [ ] Write Wrapper of Material UI Button Component
- [ ] Write Wrapper of Material UI Input Field Component

**Comment by fenilgandhi** [comment]
Can you edit the title ?

**Comment by fenilgandhi** [comment]
Hey @nimish-gupta / @rishabh1403 , me and @nitishmittal1990 both are working on this same issue but with different set of components, can we split this issue into two separate ones accordingly ?
